name: Kubernetes App - Manifests Only

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/kubernetes-app-manifests-only.yaml@1.1.14
    permissions:
      contents: write
      packages: write
      checks: write
